### ISSUE TITLE
About the pre-trained weights

### ISSUE THREAD

**Issue by SCUTJoeham** [aaai-24/Generative-based-KD#1]
Hi, Did you use the pre-trained weights to fine-tune i3d teacher on ucf101? If so, could you please share your pre-trained weights or tell me where you got it? Thank you so much!

**Comment by aaai-24** [comment]
Hello @SCUTJoeham , thanks for your question! Yes, we use teacher weight pre-trained on imagenet to fine-tune on UCF101, HMDB51 and THUMOS14. You can find the pre-trained weight [here](https://github.com/piergiaj/pytorch-i3d/tree/master/models).
